Update CircleCI
Cyber4All/download-test-client pull request #10
Opened 2022-01-20 18:51 UTC by StarChaser44

2022-01-20 19:00 UTC, Cwagne17 requested changes

2022-01-20 19:01 UTC, Cwagne17 commented on .circleci/config.yml
> +                command: export KEY=$AWS_LAMBDA_SecretKey
also I don't believe the $ is necessary, we haven't had to use that for other declarations

2022-02-03 14:28 UTC, pzalep1 approved these changes

2022-02-03 14:49 UTC, EVogel1999 approved these changes

2022-02-03 19:29 UTC, jouypo23 approved these changes

2022-02-04 15:58 UTC, Cwagne17 approved these changes
We don't need jq anymore it looks like also.

2022-02-04 17:26 UTC, merged